### ISSUE TITLE
API key reconfigure

### ISSUE THREAD

**Issue by JacobSeatlholo** [msadiq10/ChatGPTClone#1]
I see the current API key has reached its quota and I'm now trying to reconfigure it to mine however the new .env file isn't picking this up?. any help?.

**Comment by msadiq10** [comment]
OPENAI_API_KEY = "YOUR_API_KEY"

Your .env should contain the above line. Replace "YOUR_API_KEY" with your actual OpenAI API key. Also make sure your .env file is in the `server` folder.
